# Form implementation generated from reading ui file 'ui/mainFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QLabel, QGraphicsOpacityEffect
from PyQt6.QtCore import QTimer, Qt
from PyQt6.QtGui import QFont

class loadingFrame(QMainWindow):
    def __init__(self, switch_callback=None):
        super().__init__()

        self.setObjectName("mainFrame")
        self.resize(800, 600)
        
        self.setWindowOpacity(0.9) 
        
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.centerLayoutH = QtWidgets.QHBoxLayout()
        self.centerLayoutH.setObjectName("centerLayoutH")

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.centerLayoutH.addItem(spacerItem)

        self.centerLayoutV = QtWidgets.QVBoxLayout()
        self.centerLayoutV.setObjectName("centerLayoutV")

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.centerLayoutV.addItem(spacerItem1)

        self.centerFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.centerFrame.setMinimumSize(QtCore.QSize(800, 480))
        self.centerFrame.setMaximumSize(QtCore.QSize(800, 480))    
        self.centerFrame.setStyleSheet("QFrame#centerFrame {\n"
            "   background-image: url('./resources/Transparent Truck Cartoon.png');\n"
            "   background-position: left;\n"
            "   background-repeat: no-repeat;\n"
            "   background-color: white;\n"
            "   border: 1px solid rgb(156, 163, 175);\n"
            "   border-radius: 5px;\n"
            "   padding: 1px;\n"
            "}")
        self.centerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.centerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.centerFrame.setObjectName("centerFrame")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centerFrame)
        self.verticalLayout.setObjectName("verticalLayout")

        self.loadingLayout = QtWidgets.QVBoxLayout()
        self.loadingLayout.setObjectName("loadingLayout")

        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.loadingLayout.addItem(spacerItem2)
        
        self.logoLabel = QtWidgets.QLabel(parent=self.centerFrame)
        self.logoLabel.setStyleSheet("font: 500 10pt \"Segoe UI\"; color: rgb(55, 65, 81);")
        self.logoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setText("DIEGA - TAPPA")
        self.loadingLayout.addWidget(self.logoLabel)

        # Main Title Label
        self.label = QtWidgets.QLabel(parent=self.centerFrame)
        self.label.setStyleSheet("font: 800 30pt \"Segoe UI\"; color: rgb(55, 65, 81);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.loadingLayout.addWidget(self.label)
        
        self.statusLabel = QtWidgets.QLabel(parent=self.centerFrame)
        self.statusLabel.setStyleSheet("font: 500 10pt \"Segoe UI\"; color: rgb(55, 65, 81);")
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.statusLabel.setText("Initializing application...")
        self.loadingLayout.addWidget(self.statusLabel)

        # Spacer
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.loadingLayout.addItem(spacerItem3)

        self.versionLabel = QtWidgets.QLabel(parent=self.centerFrame)
        self.versionLabel.setStyleSheet("font: 400 8pt \"Segoe UI\"; color: black;")
        self.versionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom | QtCore.Qt.AlignmentFlag.AlignRight)
        self.versionLabel.setText("Version 1.0.0 | Build M0030") 
        self.loadingLayout.addWidget(self.versionLabel)
        
        self.verticalLayout.addLayout(self.loadingLayout)
        self.centerLayoutV.addWidget(self.centerFrame)

        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.centerLayoutV.addItem(spacerItem4)

        self.centerLayoutV.setStretch(0, 1)
        self.centerLayoutV.setStretch(1, 3)
        self.centerLayoutV.setStretch(2, 1)
        self.centerLayoutH.addLayout(self.centerLayoutV)

        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.centerLayoutH.addItem(spacerItem5)

        self.centerLayoutH.setStretch(0, 1)
        self.centerLayoutH.setStretch(1, 3)
        self.centerLayoutH.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.centerLayoutH)
        self.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")

        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(switch_callback)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, switch_callback):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("mainFrame", "TruckCane AI"))
        self.label.setText(_translate("MainWindow", "TRUCKCANE AI"))

        self.loadStep = 0
        self.loadSteps = [15, 45, 75, 95, 100]
        self.statusMessages = [
            "Initializing Raspberry Pi 5...",
            "Initializing Camera Module...",
            "Initializing Touch Display...",
            "Loading YOLOv11 Model...",
            "Loading Graphic User Interface..."
        ]
        
        #Delay
        self.timer = QTimer()
        self.timer.timeout.connect(lambda: self.fakeLoad(switch_callback))
        self.timer.start(500)

    def fakeLoad(self, switch_callback):
        if self.loadStep < len(self.loadSteps):
            #self.progressBar.setValue(self.loadSteps[self.loadStep])
            
            self.statusLabel.setText(self.statusMessages[self.loadStep])
            
            self.loadStep += 1
        else:
            switch_callback("main")
            self.timer.stop()