# Form implementation generated from reading ui file 'ui/cameraFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
import numpy as np
import pickle
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QMessageBox, QInputDialog, QDialog, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QSpacerItem
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QPixmap, QPainter, QPen, QImage, QColor, QFont
from ultralytics import YOLO

def resource_path(relative_path):
    if hasattr(sys, '_MEIPASS'):
        base_path = sys._MEIPASS
    else:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

directory = resource_path("images")
#directory = "./images/"
os.makedirs(directory, exist_ok=True)

#custom saved dialog box
class SavedMessageDialog(QDialog):
    def __init__(self, message, parent=None):
        super().__init__(parent)
        
        self.setWindowTitle("Saved")
        self.setFixedSize(350, 150)
        self.setModal(True)              
        self.setObjectName("SavedMessageDialog")

        self.mainLayout = QVBoxLayout(self)
        self.mainLayout.setSpacing(15)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)

        self.messageLabel = QLabel(message, self)
        self.messageLabel.setObjectName("messageLabel")
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.messageLabel.setStyleSheet("""
                QLabel#messageLabel {
                    background-color: white;
                    color: #1f2937; /* Dark Gray text */
                    font: 500 11pt "Segoe UI";
                }
            """)
        
        self.mainLayout.addWidget(self.messageLabel)

        self.buttonLayout = QHBoxLayout()
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)

        self.okButton = QPushButton("OK", self)
        self.okButton.setObjectName("okButton")
        self.okButton.setFixedSize(80, 30)
        
        self.okButton.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 6 px 6px; \n"
            "    font: 600 12pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")
        
        self.okButton.clicked.connect(self.accept) # Connects to the standard accept/close function

        self.buttonLayout.addWidget(self.okButton)
        self.mainLayout.addLayout(self.buttonLayout)
        
        self.setStyleSheet("""
                QDialog#SavedMessageDialog {
                    background-color: white; 
                    border: 1px solid rgb(156, 163, 175);
                    border-radius: 8px;
                    margin: 5px;
                }
            """)

#custom confirm discard dialog box
class ConfirmDialog(QDialog):
    def __init__(self, title, message, parent=None):
        super().__init__(parent)
        
        self.setWindowTitle(title)
        self.setFixedSize(350, 150)
        self.setModal(True)
        self.setObjectName("ConfirmDialog")
        
        self.mainLayout = QVBoxLayout(self)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        
        self.messageLabel = QLabel(message, self)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.messageLabel.setStyleSheet("""
                QLabel {
                    color: #1f2937; /* Dark Gray text */
                    font: 500 11pt "Segoe UI";
                }
            """)
        self.mainLayout.addWidget(self.messageLabel)
        
        self.buttonLayout = QHBoxLayout()
        self.buttonLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.noButton = QPushButton("No", self)
        self.noButton.setObjectName("noButton")
        self.noButton.setFixedSize(80, 30)
        self.noButton.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 6 px 6px; \n"
            "    font: 600 12pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")

        self.noButton.clicked.connect(self.reject) 
        self.buttonLayout.addWidget(self.noButton)

        self.yesButton = QPushButton("Yes", self)
        self.yesButton.setObjectName("yesButton")
        self.yesButton.setFixedSize(80, 30)
        self.yesButton.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 6 px 6px; \n"
            "    font: 600 12pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")

        self.yesButton.clicked.connect(self.accept) 
        self.buttonLayout.addWidget(self.yesButton)

        self.mainLayout.addLayout(self.buttonLayout)
        
        self.setStyleSheet("""
                QDialog#ConfirmDialog {
                    background-color: white; 
                    border: 1px solid rgb(156, 163, 175);
                    border-radius: 8px;
                    margin: 5px;
                }
            """)

class analysisFrame(QMainWindow):
    def __init__(self, switch_callback=None):
        super().__init__()

        self.model = YOLO(resource_path('./resources/truck-cane-ai-training-4-model_ncnn_model'), task = 'detect')
        
        self.setObjectName("mainFrame")
        self.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.centerLayoutH = QtWidgets.QHBoxLayout()
        self.centerLayoutH.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.centerLayoutH.setContentsMargins(-1, -1, -1, 0)
        self.centerLayoutH.setSpacing(6)
        self.centerLayoutH.setObjectName("centerLayoutH")

        self.centerLayoutV = QtWidgets.QVBoxLayout()
        self.centerLayoutV.setObjectName("centerLayoutV")

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.centerLayoutV.addItem(spacerItem1)

        self.centerFrame = QtWidgets.QFrame(parent=self.centralwidget)
        #self.centerFrame.setMaximumSize(QtCore.QSize(800, 480))
        self.centerFrame.setStyleSheet("QFrame#centerFrame {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 8px; \n"
            "    padding: 5px; \n"
            "}")

        self.centerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.centerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.centerFrame.setObjectName("centerFrame")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centerFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.centerLayout = QtWidgets.QVBoxLayout()
        self.centerLayout.setObjectName("centerLayout")

        self.panelLayout = QtWidgets.QHBoxLayout()
        self.panelLayout.setObjectName("panelLayout")
        self.panel1 = QtWidgets.QVBoxLayout()
        self.panel1.setObjectName("panel1")

        self.cameraLabel = QtWidgets.QLabel(parent=self.centerFrame)
        self.cameraLabel.setStyleSheet("QFrame#cameraLabel {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid #d2d6db ; \n"
            "    border-radius: 8px; \n"
            "    padding: 8px; \n"
            "}")
        self.cameraLabel.setObjectName("cameraLabel")
        self.cameraLabel.setMinimumSize(QtCore.QSize(402,288))

        self.panel1.addWidget(self.cameraLabel)
        self.panelLayout.addLayout(self.panel1)
        self.panel2 = QtWidgets.QVBoxLayout()
        self.panel2.setObjectName("panel2")

        self.analysisLabel = QtWidgets.QLabel(parent=self.centerFrame)
        self.analysisLabel.setStyleSheet("QFrame#analysisLabel {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid #d2d6db ; \n"
            "    border-radius: 8px; \n"
            "    padding: 5px;\n"
            "    color: black;\n"
            "    font: ;\n"
            "    font: 400 9pt \"Segoe UI\";\n"
            "}")
        self.analysisLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.analysisLabel.setObjectName("analysisLabel")
        self.panel2.addWidget(self.analysisLabel)

        self.resultsVLayout = QtWidgets.QVBoxLayout()
        self.resultsVLayout.setContentsMargins(0, 0, 0, 0)        

        # LAYOUT for Final Result
        self.resultLayoutH = QtWidgets.QVBoxLayout() 
        self.resultLayoutH.setObjectName("resultLayoutH")
        self.resultsVLayout.addLayout(self.resultLayoutH)

        # LAYOUT for Confidence Scores
        self.confidenceContainer = QtWidgets.QWidget(parent=self.centerFrame)
        self.confidenceContainer.setObjectName("confidenceContainer")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, 
            QtWidgets.QSizePolicy.Policy.Expanding
        )
        self.confidenceContainer.setSizePolicy(sizePolicy)  

        self.confidenceContainer.setStyleSheet("""
                QWidget#confidenceContainer {
                    background-color: rgb(255, 255, 255); 
                    border: 1px solid #d2d6db; 
                    border-radius: 8px; 
                    padding: 10px; /* Padding inside the container */
                }
            """)

        self.objectsLayout = QtWidgets.QVBoxLayout(self.confidenceContainer)
        self.objectsLayout.setObjectName("objectsLayout")
        self.objectsLayout.setSpacing(0)

        self.resultsVLayout.addWidget(self.confidenceContainer)
        self.panel2.addLayout(self.resultsVLayout)   
 
        self.panel2.setStretch(0, 0)
        self.panel2.setStretch(1, 1) 
        self.panelLayout.addLayout(self.panel2)
        
        self.panelLayout.setStretch(0, 1)
        self.panelLayout.setStretch(1, 1)
        self.centerLayout.addLayout(self.panelLayout)

        spacerItem2 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.centerLayout.addItem(spacerItem2)

        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")

        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem3)

        self.saveButton = QtWidgets.QPushButton(parent=self.centerFrame)
        self.saveButton.setStyleSheet("QPushButton {\n"
            "    background-color: rgb(0, 162, 0);  \n"
            "    color: white; \n"
            "    border-radius: 5px;\n"
            "    padding: 8 px 8px; \n"
            "    font: 600 11pt \"Segoe UI\";\n"
            "    max-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(0, 200, 0);\n"
            "    color: white; \n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 140, 0);\n"
            "    color: white;\n"
            "    border: none;\n"
            "    padding-top: 9px;\n"
            "    padding-bottom: 7px;\n"
            "}")
        self.saveButton.setObjectName("saveButton")
        self.buttonsLayout.addWidget(self.saveButton)

        self.backButton = QtWidgets.QPushButton(parent=self.centerFrame)
        self.backButton.setStyleSheet("QPushButton {\n"
            "    background-color: rgb(222, 0, 0);  \n"
            "    color: white; \n"
            "    border-radius: 5px;\n"
            "    padding: 8 px 8px; \n"
            "    font: 600 11pt \"Segoe UI\";\n"
            "    max-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(255, 30, 30);\n"
            "    color: white; \n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(180, 0, 0);\n"
            "    color: white;\n"
            "    border: none;\n"
            "    padding-top: 9px;\n"
            "    padding-bottom: 7px; \n"
            "}")        
        self.backButton.setObjectName("backButton")
        self.buttonsLayout.addWidget(self.backButton)

        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem4)
        
        self.buttonsLayout.setStretch(0, 1)
        self.buttonsLayout.setStretch(1, 1)
        self.buttonsLayout.setStretch(2, 1)
        self.buttonsLayout.setStretch(3, 1)

        self.centerLayout.addLayout(self.buttonsLayout)
        self.centerLayout.setStretch(0, 10)
        self.centerLayout.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.centerLayout)
        self.centerLayoutV.addWidget(self.centerFrame)

        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.centerLayoutV.addItem(spacerItem5)

        self.centerLayoutV.setStretch(0, 1)
        self.centerLayoutV.setStretch(1, 6)
        self.centerLayoutV.setStretch(2, 1)
        self.centerLayoutH.addLayout(self.centerLayoutV)

        self.verticalLayout_2.addLayout(self.centerLayoutH)
        self.verticalLayout_2.setStretch(0, 1)
        self.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 22))
        self.menubar.setObjectName("menubar")
        
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.saveButton.clicked.connect(lambda: self.saveFunc(switch_callback))
        self.backButton.clicked.connect(lambda: self.backFunc(switch_callback))
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "TruckCane AI"))
        self.cameraLabel.setText(_translate("self", "Camera"))
        self.analysisLabel.setText(_translate("self", "Image Size: ()"))
        self.saveButton.setText(_translate("self", "Save"))
        self.backButton.setText(_translate("self", "Discard"))

    def saveFunc(self, switch_callback):
        if self.filename == "":
            timestamp_str = self.data[1].strftime("%Y-%m-%d_%H-%M-%S")
            save_path = os.path.join(directory, f"image_{timestamp_str}.jpg")
            self.data[0].save(save_path)
            save_path = os.path.join(directory, f"predictions/image_{timestamp_str}.pkl")
            with open(save_path, "wb") as f:
                pickle.dump(self.results, f)

            #new_fname, ok = QInputDialog.getText(None, "Enter filename", "Name: ", text=f"image_{self.data[1].timestamp()}")
            #if ok:
            #    save_path = os.path.join(directory, f"{new_fname}.jpg")
            #    self.data[0].save(save_path)
            #    save_path = os.path.join(directory, f"predictions/{new_fname}.pkl")
            #    with open(save_path, "wb") as f:
            #        pickle.dump(self.results, f)
            #else:
            #    return
        else:
            save_path = os.path.join(directory, f"predictions/{self.filename}.pkl")
            with open(save_path, "wb") as f:
                pickle.dump(self.results, f)
        
        #msg = QMessageBox(self)
        #msg.setFixedWidth(500)
        #msg.setWindowTitle("Saved")
        #msg.setText("Results saved!")
        #msg.setStandardButtons(QMessageBox.StandardButton.Ok)
        #msg.exec()
        
        msg = SavedMessageDialog("Image and detection results saved successfully!", parent=self)
        msg.exec()

        sauce = "cam" if self.filename == "" else "files"
        switch_callback("view", self.data[0], self.data[1], self.results, sauce)
    
    def loadImage(self, qt_img: QPixmap, timestamp, filename:str):
        self.data = [qt_img, timestamp]
        self.filename = filename
        if filename == "":
            _translate = QtCore.QCoreApplication.translate
            self.backButton.setText(_translate("self", "Discard"))
        else:
            _translate = QtCore.QCoreApplication.translate
            self.backButton.setText(_translate("self", "Back"))

        img = qt_img.convertToFormat(QImage.Format.Format_RGB888)
        h, w = img.height(), img.width()
        ptr = img.bits()
        ptr.setsize(h * w * 3)
        img_np = np.array(ptr, dtype=np.uint8).reshape((h, w, 3))

        results_raw = self.model(img_np)
        self.results = [[], self.model.names]
        for result in results_raw:
            boxes = result.boxes.xyxy.cpu().numpy()
            classes = result.boxes.cls.cpu().numpy().astype(int)
            confs = result.boxes.conf.cpu().numpy()
            self.results[0].append({
                "boxes": boxes,
                "classes": classes,
                "confs": confs
            })

        out_pix = QPixmap(qt_img)

        # Image Size
        text = "Image Size:" + "\t\t" + "(" + str(out_pix.width()) + ", " + str(out_pix.height()) + ")\n"
        # Image Date
        text += "Capture Date & Time:" + "\t" + timestamp.strftime('%B %d %Y - %I:%M %p') + "\n"
        self.analysisLabel.setText(text)

        self.clearLayout(self.objectsLayout)
        if len(self.results[0][0]["boxes"].tolist()) == 0:
            scaled_pix = out_pix.scaled(
                self.cameraLabel.size(),
                Qt.AspectRatioMode.KeepAspectRatio,
                Qt.TransformationMode.SmoothTransformation
            )
            self.cameraLabel.setPixmap(scaled_pix)

            self.analysisLabel.setText(text + "Nothing detected.")
            self.clearLayout(self.resultLayoutH)
            return

        #confidenceTitle
        self.confidenceTitleLabel = QtWidgets.QLabel(parent=self.centerFrame)
        self.confidenceTitleLabel.setObjectName("confidenceTitleLabel")
        self.confidenceTitleLabel.setText(self.tr("Confidence Level:")) 
        self.confidenceTitleLabel.setStyleSheet("QLabel#confidenceTitleLabel {\n"
            "    color: rgb(55, 65, 81); \n"
            "    font: 600 11pt \"Bahnschrift\"; color: rgb(55, 65, 81); \n" 
            "}\n")
        
        self.objectsLayout.addWidget(self.confidenceTitleLabel)

        class_colors = [
            QColor(255, 0, 0),    # Red
            QColor(255, 0, 255),  # Magenta
            QColor(0, 0, 255),    # Blue
            QColor(255, 255, 0),  # Yellow
            QColor(255, 128, 0),  # Orange 
            QColor(0, 255, 0),    # Green            
            QColor(0, 255, 255),  # Cyan
        ]

        painter = QPainter(out_pix)

        #scale_factor = out_pix.width() / 640.0

        font = QFont()
        font.setPointSize(22)
        font.setBold(True)
        painter.setFont(font)

        # Results
        conds = [0, 0, 0]
        for result in self.results[0]:
            boxes = result["boxes"]
            classes = result["classes"]
            confs = result["confs"]
            names = self.results[1]

            names_num = {}
            names_count = {}
            for cls in classes:
                names_num[names[cls]] = 1 if not names[cls] in names_num.keys() else names_num[names[cls]] + 1
                names_count[names[cls]] = 1
            num = 0
            for box, cls, conf in zip(boxes, classes, confs):
                x1, y1, x2, y2 = box
                color = class_colors[cls % len(class_colors)]
                pen = QPen(color)
                pen.setWidth(5)
                painter.setPen(pen)
                painter.drawRect(int(x1), int(y1), int(x2 - x1), int(y2 - y1))

                painter.setPen(color)
                name = names[cls] + ((" " + str(names_count[names[cls]])) if names_num[names[cls]] > 1 else "")
                names_count[names[cls]] += 1

                #offset = int(5 * scale_factor) + 5
                painter.drawText(int(x1), int(y1) - 15, name)

                conds[0] = 1 if names[cls] == "sugarcane-carrying-truck" else conds[0]
                conds[1] = 1 if names[cls] == "overhanging-load" else conds[1]
                conds[2] = 1 if names[cls] == "overheight-load" else conds[2]

                #class label for confidence score
                self.object = QtWidgets.QHBoxLayout()
                self.object.setObjectName("object")
                self.objectLabel = QtWidgets.QLabel(parent=self.centerFrame)
                self.objectLabel.setStyleSheet("QLabel#objectLabel {\n"
                    "    color: rgb(55, 65, 81);\n"
                    "    background-color: white; \n"
                    "    font: 600 9pt \"Segoe UI\";\n"
                    "    margin-top: 10px; \n"
                    "}\n")                

                self.objectLabel.setObjectName("objectLabel")
                self.objectLabel.setText(name)
                self.object.addWidget(self.objectLabel)

                #confidence score progress bar
                self.objectConf = QtWidgets.QProgressBar(parent=self.centerFrame)
                self.objectConf.setFixedWidth(130)
                self.objectConf.setStyleSheet("QProgressBar#objectConf {\n"
                    "    text-align: center; \n"
                    "    background: white; \n"
                    "    color: white; \n"
                    "    border: 1px solid #9ca3af;\n"
                    "    border-radius: 6px;\n"
                    "    height: 12px;\n"
                    "    margin-left: 2px; \n"                    
                    "    margin-top: 10px; \n"
                    "}\n"
                    "\n"
                    "QProgressBar#objectConf::chunk {\n"
                    "    background-color: #bae6fd; \n"
                    "    border: 1px solid #0284c7;\n"
                    "    border-radius: 6px; \n"                
                    "}\n"
                    )                      
                self.objectConf.setProperty("value", int(conf*100.0))
                self.objectConf.setFormat("")
                self.objectConf.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
                self.objectConf.setInvertedAppearance(True)
                self.objectConf.setObjectName("objectConf")
                self.object.addWidget(self.objectConf)
                self.objectsLayout.addLayout(self.object)

                #confidence score percentage
                self.percentLabel = QtWidgets.QLabel(parent=self.centerFrame)
                self.percentLabel.setFixedWidth(45)
                self.percentLabel.setStyleSheet("QLabel#percentLabel {\n"
                    "    color: #0284c7;\n"
                    "    background-color: white; \n"
                    "    font: 600 9pt \"Bahnschrift\";\n"
                    "    margin-left: 10px; \n"
                    "    margin-top: 10px; \n"
                    "}\n")
                self.percentLabel.setObjectName("percentLabel")
                self.percentLabel.setText(f"{int(conf*100.00)}%")
                self.object.addWidget(self.percentLabel)
                self.object.addWidget(self.objectConf)                
                num += 1               
        
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.objectsLayout.addItem(spacerItem7)
        
        # Detection Count
        text += "Objects Detected:" + "\t" + str(num)
        self.analysisLabel.setText(text)

        #FINAL RESULT CSS
        SAFE_COLOR = "color: #059669; font: 800 14pt \"Bahnschrift\";"
        UNSAFE_COLOR = "color: #dc2626; font: 800 14pt \"Bahnschrift\";"
        REGULAR_FONT = "font: 600 11pt \"Bahnschrift\"; color: rgb(55, 65, 81);"
        
        self.clearLayout(self.resultLayoutH)
        
        status_container = QtWidgets.QWidget(parent=self.centerFrame)
        status_container.setObjectName("statusContainer")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        status_container.setSizePolicy(sizePolicy)
        
        status_container.setStyleSheet("""
            QWidget#statusContainer {
                border: 1px solid #d2d6db;
                background-color: rgb(255, 255, 255);
                border-radius: 8px;
            }
        """)

        status_vlayout = QtWidgets.QVBoxLayout(status_container)
        status_vlayout.setSpacing(3)
        
        result_prefix_label = QtWidgets.QLabel() 
        result_prefix_label.setText("Result:")
        
        result_prefix_label.setStyleSheet(REGULAR_FONT) 
        result_prefix_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        status_vlayout.addWidget(result_prefix_label)

        status_label = QtWidgets.QLabel()
        
        if conds[1] or conds[2]:
            status_label.setText("UNSAFE")
            status_label.setStyleSheet(UNSAFE_COLOR) 
        else:
            status_label.setText("SAFE")
            status_label.setStyleSheet(SAFE_COLOR) 
            
        status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        status_vlayout.addWidget(status_label)
        
        self.resultLayoutH.addWidget(status_container)
        
        self.analysisLabel.setText(text)
        #

        painter.end()
        
        scaled_pix = out_pix.scaled(
            self.cameraLabel.size(),
            Qt.AspectRatioMode.KeepAspectRatio,
            Qt.TransformationMode.SmoothTransformation
        )
        self.cameraLabel.setPixmap(scaled_pix)
    
    def backFunc(self, switch_callback):
        if self.filename == "":
            #msg = QMessageBox(self)
            #msg.setWindowTitle("Confirm")
            #msg.setText("Are you sure?")
            #msg.setStandardButtons(QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)
            #res = msg.exec()

            msg = ConfirmDialog("Confirm", "Unsaved analysis will be lost. Do you wish to continue?", parent=self)
            res = msg.exec() # Executes the dialog and waits for user input            

            if res == QtWidgets.QDialog.DialogCode.Accepted: 
                            switch_callback("camera")
        else:
            switch_callback("files")
    
    def clearLayout(self, layout):
        while layout.count():
            item = layout.takeAt(0)
            if item.widget():
                item.widget().setParent(None)
            elif item.layout():
                self.clearLayout(item.layout())
