# Form implementation generated from reading ui file 'ui/cameraFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
import cv2
from datetime import datetime
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow
from PyQt6.QtCore import QTimer, Qt
from PyQt6.QtGui import QPixmap, QImage

from picamera2 import Picamera2

def resource_path(relative_path):
    if hasattr(sys, '_MEIPASS'):  # Running from exe
        base_path = sys._MEIPASS
    else:  # Running from source
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

directory = resource_path("images")
os.makedirs(directory, exist_ok=True)

class cameraFrame(QMainWindow):
    def __init__(self, switch_callback=None):
        super().__init__()
        
        self.cap = None
        self.captured = False
        self.isDisplayed = False
        self.state = 0
        self.qt_img = None
        
        self.setObjectName("mainFrame")
        self.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")

        spacerItem = QtWidgets.QSpacerItem(214, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        #self.frame.setMaximumSize(QtCore.QSize(800, 480))        
        self.frame.setStyleSheet("QFrame#frame {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px; \n"
            "    padding: 5px; \n"
            "}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.Panel1 = QtWidgets.QVBoxLayout()
        self.Panel1.setObjectName("Panel1")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        spacerItem2 = QtWidgets.QSpacerItem(200, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)

        self.Panel1.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        spacerItem3 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem3)

        self.cameraLabel = QtWidgets.QLabel(parent=self.frame)
        self.cameraLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.cameraLabel.setMinimumSize(QtCore.QSize(415, 303))
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")
        self.cameraLabel.setStyleSheet("QFrame#cameraLabel {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid #d2d6db; \n"
            "    border-radius: 5px; \n"
            "    padding: 5px; \n"
            "}")

        self.horizontalLayout_6.addWidget(self.cameraLabel)
        self.horizontalLayout_6.setStretch(1, 1)

        self.Panel1.addLayout(self.horizontalLayout_6)
        self.Panel1.setStretch(1, 1)

        self.horizontalLayout_2.addLayout(self.Panel1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)  

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
            "    background-color: rgb(0, 162, 0);  \n"
            "    color: white; \n"
            "    border-radius: 5px;\n"
            "    padding: 8 px 8px; \n"
            "    font: 600 11pt \"Segoe UI\";\n"
            "    max-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(0, 200, 0);\n"
            "    color: white; \n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(0, 140, 0);\n"
            "    color: white;\n"
            "    border: none;\n"
            "    padding-top: 9px;\n"
            "    padding-bottom: 7px;\n"
            "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)

        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setStyleSheet("QPushButton {\n"
            "    background-color: rgb(222, 0, 0);  \n"
            "    color: white; \n"
            "    border-radius: 5px;\n"
            "    padding: 8 px 8px; \n"
            "    font: 600 11pt \"Segoe UI\";\n"
            "    max-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: rgb(255, 30, 30);\n"
            "    color: white; \n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: rgb(180, 0, 0);\n"
            "    color: white;\n"
            "    border: none;\n"
            "    padding-top: 9px;\n"
            "    padding-bottom: 7px; \n"
            "}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)

        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)

        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)

        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.setStretch(0, 10)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.frame)

        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem7)

        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)

        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)

        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)

        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 22))
        self.menubar.setObjectName("menubar")
        
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(lambda: self.button2Func(switch_callback))
        self.pushButton_2.clicked.connect(lambda: self.button1Func(switch_callback))
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "TruckCane AI"))
        self.pushButton_2.setText(_translate("self", "Capture"))
        self.pushButton.setText(_translate("self", "Back"))
        
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_frame)
        self.timer.start(30)
    
    def update_frame(self):
        if not self.captured and self.isDisplayed and self.cap != None:
            try:
                frame = self.cap.capture_array()
                
                h, w, ch = frame.shape
                bytes_per_line = ch * w
                
                self.qt_img = QImage(frame.data, w, h, bytes_per_line, QImage.Format.Format_RGB888)
                
                pix = QPixmap.fromImage(self.qt_img)

                scaled_pix = pix.scaled(
                    self.cameraLabel.size(),
                    Qt.AspectRatioMode.KeepAspectRatio,
                    Qt.TransformationMode.SmoothTransformation
                )
                self.cameraLabel.setPixmap(scaled_pix)

            except Exception as e:
                pass
    
    def showEvent(self, event):
        if self.cap is None:
            self.cap = Picamera2()
            
            config = self.cap.create_video_configuration(
                main={"size": (1920, 1080), "format": "BGR888"}
            )
            self.cap.configure(config)
            self.cap.start()
            self.isDisplayed = True
        super().showEvent(event)

    def closeEvent(self, event):
        if self.cap is not None:
            self.isDisplayed = False
            self.cap.stop()
            self.cap.close()
            self.cap = None
        super().closeEvent(event)

    def resumeCam(self):
        if self.cap is None:
            self.captured = False
            self.isDisplayed = True

    def button1Func(self, switch_callback):
        _translate = QtCore.QCoreApplication.translate
        match self.state:
            case 0:
                frame = self.cap.capture_array()
                
                self.cap.stop()

                h, w, ch = frame.shape
                bytes_per_line = ch * w
                
                self.qt_img = QImage(frame.data, w, h, bytes_per_line, QImage.Format.Format_RGB888).copy()

                pix = QPixmap.fromImage(self.qt_img)
                scaled_pix = pix.scaled(
                    self.cameraLabel.size(),
                    QtCore.Qt.AspectRatioMode.KeepAspectRatio,
                    QtCore.Qt.TransformationMode.SmoothTransformation
                )
                self.cameraLabel.setPixmap(scaled_pix)

                self.captured = True
                self.state = 1
                self.pushButton_2.setText(_translate("self", "Predict"))
                self.pushButton.setText(_translate("self", "Cancel"))

            case 1:
                if self.cap is not None:
                    self.cap.close()
                    self.cap = None
                
                self.captured = False
                self.state = 0
                self.pushButton_2.setText(_translate("self", "Capture"))
                self.pushButton.setText(_translate("self", "Back"))
                
                switch_callback("analysis", self.qt_img, datetime.now(), sauce="")
    
    def button2Func(self, switch_callback):
        _translate = QtCore.QCoreApplication.translate
        match self.state:
            case 0:
                self.isDisplayed = False
                if self.cap is not None:
                    self.cap.stop()
                    self.cap.close()
                    self.cap = None
                switch_callback("main")
            case 1:
                if self.cap is not None:
                    self.cap.start()         
                       
                self.captured = False
                self.state = 0
                self.pushButton_2.setText(_translate("self", "Capture"))
                self.pushButton.setText(_translate("self", "Back"))
