# Form implementation generated from reading ui file 'ui/mainFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os
import numpy as np
import pickle
from datetime import datetime
from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QMessageBox, QInputDialog, QDialog, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QSpacerItem
from PyQt6.QtGui import QImage, QFont

def resource_path(relative_path):
    if hasattr(sys, '_MEIPASS'):
        base_path = sys._MEIPASS
    else:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

directory = resource_path("images")
#directory = "./images/"
os.makedirs(directory, exist_ok=True)

#custom confirm delete dialog box
class ConfirmDialog(QDialog):
    def __init__(self, title, message, parent=None):
        super().__init__(parent)

        self.setWindowTitle(title)
        self.setFixedSize(350, 150)
        self.setModal(True)
        self.setObjectName("ConfirmDialog")
        
        self.mainLayout = QVBoxLayout(self)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        
        self.messageLabel = QLabel(message, self)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.messageLabel.setStyleSheet("""
                QLabel {
                    color: #1f2937; /* Dark Gray text */
                    font: 500 11pt "Segoe UI";
                }
            """)
        self.mainLayout.addWidget(self.messageLabel)
        
        self.buttonLayout = QHBoxLayout()
        self.buttonLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        
        self.noButton = QPushButton("No", self)
        self.noButton.setObjectName("noButton")
        self.noButton.setFixedSize(80, 30)
        self.noButton.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 6 px 6px; \n"
            "    font: 600 12pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")

        self.noButton.clicked.connect(self.reject) 
        self.buttonLayout.addWidget(self.noButton)

        self.yesButton = QPushButton("Yes", self)
        self.yesButton.setObjectName("yesButton")
        self.yesButton.setFixedSize(80, 30)
        self.yesButton.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 6 px 6px; \n"
            "    font: 600 12pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")

        self.yesButton.clicked.connect(self.accept) 
        self.buttonLayout.addWidget(self.yesButton)

        self.mainLayout.addLayout(self.buttonLayout)
        
        self.setStyleSheet("""
                QDialog#ConfirmDialog {
                    background-color: white; 
                    border: 1px solid rgb(156, 163, 175);
                    border-radius: 8px;
                    margin: 5px;
                }
            """)

class filesFrame(QMainWindow):
    def __init__(self, switch_callback=None):
        super().__init__()
        
        self.setObjectName("mainFrame")
        self.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.mainHLayout = QtWidgets.QHBoxLayout()
        #self.mainHLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.mainHLayout.setContentsMargins(-1, -1, -1, 0)
        self.mainHLayout.setSpacing(6)
        self.mainHLayout.setObjectName("mainHLayout")

        spacerItem = QtWidgets.QSpacerItem(214, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.mainHLayout.addItem(spacerItem)

        self.mainVLayout = QtWidgets.QVBoxLayout()
        self.mainVLayout.setObjectName("mainVLayout")

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainVLayout.addItem(spacerItem1)

        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        #self.frame.setMinimumSize(QtCore.QSize(800, 480))
        self.frame.setMaximumSize(QtCore.QSize(800, 480))
        self.frame.setStyleSheet("QFrame#frame {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px; \n"
            "    padding: 20px; \n"
            "}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.frameLayout = QtWidgets.QVBoxLayout()
        self.frameLayout.setSpacing(6)
        self.frameLayout.setObjectName("frameLayout")
        
        self.filesContainer = QtWidgets.QHBoxLayout()
        self.filesContainer.setObjectName("filesContainer")

        spacerItem2 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.filesContainer.addItem(spacerItem2)

        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.scrollArea.setStyleSheet("QScrollArea#scrollArea {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid #d2d6db;\n"
            "    border-radius: 5px; \n"
            "    padding: 5px; \n"
            "}\n"
            "\n"
            "QScrollArea#scrollArea * {\n"
            "    background: transparent;\n"
            "}\n"
            "QScrollBar:vertical {\n"
            "    border: none;\n"
            "    background: #EEEEEE;\n"
            "    width: 10px;\n"
            "    margin: 0px 0px 0px 0px;\n"
            "    border-radius: 5px; \n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical {\n"
            "    background: #B0B0B0;\n"
            "    min-height: 20px;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QScrollBar::handle:vertical:hover {\n"
            "    background: #999999;\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
            "    border: none;\n"
            "    background: none;\n"
            "    height: 0px;\n"
            "}\n"
            "\n"
            "QLabel {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid #d2d6db; \n"
            "    border-radius: 5px;\n"
            "    padding: 10px 10px 10px 10px; \n"
            "    font: 300 11pt \"Bahnschrift\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton#predictButton {\n"
            "    background-color: rgb(0, 162, 0);  \n"
            "    color: white; \n"
            "    border-radius: 5px;\n"
            "    padding: 8 px 8px; \n"
            "    font: 600 11pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton#predictButton:hover {\n"
            "    background-color: rgb(0, 200, 0);\n"
            "    color: white; \n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QPushButton#predictButton:pressed {\n"
            "    background-color: rgb(0, 140, 0);\n"
            "    color: white;\n"
            "    border: none;\n"
            "    padding-top: 9px;\n"
            "    padding-bottom: 7px;\n"
            "}\n"
            "\n"
            "QPushButton#deleteButton {\n"
            "    background-color: rgb(222, 0, 0);  \n"
            "    color: white; \n"
            "    border-radius: 5px;\n"
            "    padding: 8 px 8px; \n"
            "    font: 600 11pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton#deleteButton:hover {\n"
            "    background-color: rgb(255, 30, 30);\n"
            "    color: white; \n"
            "    border: none;\n"
            "}\n"
            "\n"
            "QPushButton#deleteButton:pressed {\n"
            "    background-color: rgb(180, 0, 0);\n"
            "    color: white;\n"
            "    border: none;\n"
            "    padding-top: 9px;\n"
            "    padding-bottom: 7px; \n"
            "}")        
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollList = QtWidgets.QWidget()
        self.scrollList.setGeometry(QtCore.QRect(0, 0, 345, 264))
        self.scrollList.setObjectName("scrollList")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.fileList = QtWidgets.QVBoxLayout()
        self.fileList.setObjectName("fileList")
        self.verticalLayout_2.addLayout(self.fileList)
        self.scrollArea.setWidget(self.scrollList)
        self.filesContainer.addWidget(self.scrollArea)
        self.frameLayout.addLayout(self.filesContainer)

        self.buttonContainer = QtWidgets.QVBoxLayout()
        self.buttonContainer.setObjectName("buttonContainer")
        self.backContainer = QtWidgets.QHBoxLayout()
        self.backContainer.setObjectName("backContainer")

        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.backContainer.addItem(spacerItem3)

        self.backButton = QtWidgets.QPushButton(parent=self.frame)
        self.backButton.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 8 px 8px; \n"
            "    font: 600 11pt \"Segoe UI\";\n"
            "    max-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")          
        self.backButton.setObjectName("backButton")

        self.backContainer.addWidget(self.backButton)
        self.backContainer.setStretch(0, 3)
        self.backContainer.setStretch(1, 1)

        self.buttonContainer.addLayout(self.backContainer)
        self.buttonContainer.setStretch(0, 1)

        self.frameLayout.addLayout(self.buttonContainer)
        self.frameLayout.setStretch(0, 10)
        self.frameLayout.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.frameLayout)
        self.mainVLayout.addWidget(self.frame)

        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainVLayout.addItem(spacerItem4)

        self.mainVLayout.setStretch(0, 1)
        self.mainVLayout.setStretch(1, 6)
        self.mainVLayout.setStretch(2, 1)
        self.mainHLayout.addLayout(self.mainVLayout)

        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.mainHLayout.addItem(spacerItem5)

        self.mainHLayout.setStretch(0, 1)
        self.mainHLayout.setStretch(1, 3)
        self.mainHLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.mainHLayout)
        self.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 671, 22))
        self.menubar.setObjectName("menubar")

        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.backButton.clicked.connect(lambda: switch_callback("main"))
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("mainFrame", "TruckCane AI"))
        self.backButton.setText(_translate("mainFrame", "Back"))
    
    def refreshList(self, switch_callback):
        self.clearLayout(self.fileList)

        images = [
            file for file in os.listdir(directory)
            if file.lower().endswith((".png", ".jpg"))
        ]
        images.sort(key=lambda x: os.path.getmtime(os.path.join(directory, x)), reverse=True)

        for image in images:
            fileDetails = QtWidgets.QHBoxLayout()
            fileDetails.setObjectName("fileDetails")
            fileName = QtWidgets.QLabel(parent=self.frame)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(fileName.sizePolicy().hasHeightForWidth())
            fileName.setSizePolicy(sizePolicy)
            fileName.setObjectName(image)
            fileName.setText(image)
            fileDetails.addWidget(fileName)
            fileOptions = QtWidgets.QHBoxLayout()
            fileOptions.setObjectName("fileOptions")
            deleteButton = QtWidgets.QPushButton(parent=self.frame)
            deleteButton.setObjectName("deleteButton")
            deleteButton.setText("Delete")
            fileOptions.addWidget(deleteButton)
            filename = image[:-4]
            exists = os.path.exists(os.path.join(directory, f"predictions/{filename}.pkl"))
            predictButton = QtWidgets.QPushButton(parent=self.frame)
            predictButton.setObjectName("predictButton")
            predictButton.setText("Load" if exists else "Predict")
            if exists:
                with open(os.path.join(directory, f"predictions/{filename}.pkl"), "rb") as f:
                    results = pickle.load(f)
                timestamp = datetime.fromtimestamp(os.path.getmtime(os.path.join(directory, image)))
                predictButton.clicked.connect(
                    lambda _, fname=filename, tstamp=timestamp, rslt=results: switch_callback(
                        "view", 
                        QImage(os.path.join(directory, f"{fname}.jpg")), 
                        tstamp, 
                        rslt, 
                        "files")
                )
            else:
                timestamp = datetime.fromtimestamp(os.path.getmtime(os.path.join(directory, image)))
                predictButton.clicked.connect(
                    lambda _, fname=filename, tstamp=timestamp: switch_callback(
                        "analysis", 
                        QImage(os.path.join(directory, f"{fname}.jpg")), 
                        tstamp, 
                        sauce=fname)
                )
            fileOptions.addWidget(predictButton)
            fileDetails.addLayout(fileOptions)
            fileDetails.setStretch(0, 3)
            fileDetails.setStretch(1, 1)
            self.fileList.addLayout(fileDetails)
            
            deleteButton.clicked.connect(lambda _, fd=fileDetails, fname=image, btn=deleteButton: self.deleteFile(fd, fname, btn))
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.fileList.addItem(spacerItem3)
    
    def clearLayout(self, layout):
        while layout.count():
            item = layout.takeAt(0)
            if item.widget():
                item.widget().setParent(None)
            elif item.layout():
                self.clearLayout(item.layout())

    def deleteFile(self, fd, fname, btn):
        #msg = QMessageBox(self)
        #msg.setWindowTitle("Confirm")
        #msg.setText("Are you sure?")
        #msg.setStandardButtons(QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No)
        #res = msg.exec()

        msg = ConfirmDialog("Confirm Deletion", "Do you wish to permanently delete this record?", parent=self)
        res = msg.exec()        

        #if res == QMessageBox.StandardButton.Yes:
        if res == QtWidgets.QDialog.DialogCode.Accepted:
            btn.setEnabled(False)
            self.clearLayout(fd)
            self.fileList.removeItem(fd),
            os.remove(os.path.join(directory, fname)) if os.path.exists(os.path.join(directory, fname)) else None,
            os.remove(os.path.join(directory, f"predictions/{fname[:-4]}.pkl")) if os.path.exists(os.path.join(directory, f"predictions/{fname[:-4]}.pkl")) else None
