# Form implementation generated from reading ui file 'ui/mainFrame.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, os

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow
from PyQt6.QtGui import QPixmap

def resource_path(relative_path):
    if hasattr(sys, '_MEIPASS'):  # Running from exe
        base_path = sys._MEIPASS
    else:  # Running from source
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

directory = resource_path("images")
#directory = "./images/"
os.makedirs(directory, exist_ok=True)

class mainFrame(QMainWindow):
    def __init__(self, switch_callback=None):
        super().__init__()

        pix = QPixmap(resource_path("resources/Logo.png"))
        
        self.setObjectName("mainFrame")
        self.resize(800, 480)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")

        spacerItem = QtWidgets.QSpacerItem(214, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(800, 480))
        self.frame.setStyleSheet("QFrame#frame {\n"
            "    background-color: rgb(255, 255, 255); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px; \n"
            "    padding: 20px; \n"
            "}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, 
                         QtWidgets.QSizePolicy.Policy.Expanding)
        self.label.setScaledContents(True)
        self.label.setMinimumSize(400, 100)
        self.label.setPixmap(pix.scaled(
            self.label.width(),
            self.label.height(),
            QtCore.Qt.AspectRatioMode.KeepAspectRatio
        ))

        self.verticalLayout_2.addWidget(self.label)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)  

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 6 px 6px; \n"
            "    font: 600 12pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)

        spacerItem4 = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_3.addItem(spacerItem4)

        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setStyleSheet("QPushButton {\n"
            "    background-color: white;  \n"
            "    color: rgb(55, 65, 81); \n"
            "    border: 1px solid rgb(156, 163, 175); \n"
            "    border-radius: 5px;\n"
            "    padding: 6 px 6px; \n"
            "    font: 600 12pt \"Segoe UI\";\n"
            "    min-width: 100px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #F7F7F7;\n"
            "    border: 1px solid rgb(120, 128, 140);\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #EEEEEE; /\n"
            "    border: 1px solid rgb(55, 65, 81);\n"
            "    padding-top: 11px;\n"
            "    padding-bottom: 9px;\n"
            "}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)

        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)

        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)

        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.frame)

        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.horizontalLayout.addLayout(self.verticalLayout)

        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)

        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 22))
        self.menubar.setObjectName("menubar")
        
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.pushButton_2.clicked.connect(lambda: switch_callback("camera"))
        self.pushButton.clicked.connect(lambda: switch_callback("files"))
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("mainFrame", "TruckCane AI"))
        self.label.setText(_translate("mainFrame", ""))
        self.pushButton_2.setText(_translate("mainFrame", "Open Camera"))
        self.pushButton.setText(_translate("mainFrame", "Manage Files"))
